### ISSUE TITLE
Add option to enable/disable the popout windows alert 

### ISSUE THREAD

**Issue by perez-eli** [cTrader-Guru/Indicator-Alert#1]
![image](https://user-images.githubusercontent.com/95494222/144639101-c347a2dd-3a36-4862-86ec-c28e4de802a4.png)

Please add option to enable/disable the popout windows alert (so only telegram will send alert).

thanks for the simple and great product.

**Comment by LeonardoCiaccio** [comment]
Done, don't forget to share this little gem.
